# Generated by Django 3.1.6 on 2021-02-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210207_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('doc_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.doctors')),
            ],
        ),
    ]
