# Generated by Django 3.1.6 on 2021-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='last_Comment',
            field=models.TextField(default='no comments!', max_length=500),
        ),
        migrations.AddField(
            model_name='doctors',
            name='scores_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='total_scores_sum',
            field=models.IntegerField(default=0),
        ),
    ]
