# Generated by Django 3.1.6 on 2021-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210207_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
